[package]
name = "rumpeg-scale"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Pixel format conversion and scaling for Rumpeg (libswscale counterpart)"
keywords = ["multimedia", "video", "colorspace", "simd"]
categories = ["multimedia"]

[dependencies]
rumpeg-util = { workspace = true }
