[package]
name = "rumpeg-codec"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Codec framework and implementations for Rumpeg (libavcodec counterpart)"
keywords = ["multimedia", "codec", "decoder", "encoder"]
categories = ["multimedia", "encoding"]

[dependencies]
rumpeg-util = { workspace = true }
rumpeg-h264 = { workspace = true }
rumpeg-scale = { workspace = true }
image = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
